"""campaigns and commission

Revision ID: 0b83f68ae8f4
Revises: 4d4384e5e73b
Create Date: 2026-10-05 21:22:54.987560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b83f68ae8f4'
down_revision = '4d4384e5e73b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('reward_type', sa.String(length=16), nullable=False),
    sa.Column('reward_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaign_active'), ['active'], unique=False)

    op.create_table('campaign_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('product_odoo_id', sa.Integer(), nullable=True),
    sa.Column('product_tmpl_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaign_product', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaign_product_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_product_product_odoo_id'), ['product_odoo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_product_product_tmpl_id'), ['product_tmpl_id'], unique=False)

    with op.batch_alter_table('earning', schema=None) as batch_op:
        batch_op.add_column(sa.Column('commission', sa.Numeric(precision=14, scale=2), nullable=False, server_default='0'))

    with op.batch_alter_table('earning_line', schema=None) as batch_op:
        batch_op.add_column(sa.Column('campaign_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('commission', sa.Numeric(precision=14, scale=2), nullable=False, server_default='0'))
        batch_op.create_index(batch_op.f('ix_earning_line_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_foreign_key(None, 'campaign', ['campaign_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('earning_line', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_earning_line_campaign_id'))
        batch_op.drop_column('commission')
        batch_op.drop_column('campaign_id')

    with op.batch_alter_table('earning', schema=None) as batch_op:
        batch_op.drop_column('commission')

    with op.batch_alter_table('campaign_product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_product_product_tmpl_id'))
        batch_op.drop_index(batch_op.f('ix_campaign_product_product_odoo_id'))
        batch_op.drop_index(batch_op.f('ix_campaign_product_campaign_id'))

    op.drop_table('campaign_product')
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_active'))

    op.drop_table('campaign')
    # ### end Alembic commands ###
