"""earning lines

Revision ID: 4d4384e5e73b
Revises: d7e3c05a1b84
Create Date: 2026-10-05 15:16:57.351385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d4384e5e73b'
down_revision = 'd7e3c05a1b84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('earning_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('earning_id', sa.Integer(), nullable=False),
    sa.Column('product_odoo_id', sa.Integer(), nullable=True),
    sa.Column('product_tmpl_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=512), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['earning_id'], ['earning.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('earning_line', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_earning_line_earning_id'), ['earning_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_earning_line_product_odoo_id'), ['product_odoo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_earning_line_product_tmpl_id'), ['product_tmpl_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('earning_line', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_earning_line_product_tmpl_id'))
        batch_op.drop_index(batch_op.f('ix_earning_line_product_odoo_id'))
        batch_op.drop_index(batch_op.f('ix_earning_line_earning_id'))

    op.drop_table('earning_line')
    # ### end Alembic commands ###
