"""add application fields to users

Revision ID: e071e0df80eb
Revises: e6175b90158b
Create Date: 2026-09-24 19:04:44.262342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e071e0df80eb'
down_revision = 'e6175b90158b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('promotional_channel', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('channel_url', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('audience_size', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('why_join', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('why_join')
        batch_op.drop_column('audience_size')
        batch_op.drop_column('channel_url')
        batch_op.drop_column('promotional_channel')

    # ### end Alembic commands ###
