"""catalogue tables

Revision ID: e830d8584d47
Revises: 
Create Date: 2026-09-23 18:41:29.512975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e830d8584d47'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalogue_sync',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('product_count', sa.Integer(), nullable=False),
    sa.Column('error', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('catalogue_sync', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_catalogue_sync_ok'), ['ok'], unique=False)

    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('odoo_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('list_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('category_name', sa.String(length=255), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_available'), ['available'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_odoo_id'), ['odoo_id'], unique=True)

    op.create_table('product_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('odoo_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=True),
    sa.Column('content_type', sa.String(length=64), nullable=True),
    sa.Column('missing', sa.Boolean(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_image', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_image_odoo_id'), ['odoo_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_image', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_image_odoo_id'))

    op.drop_table('product_image')
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_odoo_id'))
        batch_op.drop_index(batch_op.f('ix_product_category_id'))
        batch_op.drop_index(batch_op.f('ix_product_available'))

    op.drop_table('product')
    with op.batch_alter_table('catalogue_sync', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_catalogue_sync_ok'))

    op.drop_table('catalogue_sync')
    # ### end Alembic commands ###
